name = "meilmaol"
main = "src/index.js"
compatibility_date = "2026-06-29"

# KV Namespace (ganti ID dengan punya kamu)
[[kv_namespaces]]
binding = "EMAILS"
id = "be35ed43f014482b911d5cc5c85ccb0d"

# Variables (bisa dilihat publik, jangan taruh secret di sini!)
[vars]
ADMIN_USERNAME = "s3lvnvmmasa"
ADMIN_USER_ID = "5085531353"
CHANNEL_ID = "-1003274298920"
GROUP_ID = "-1003245780019"
WEBMAIL_URL = "https://meilmaol.dikenyoed31.workers.dev"  # Opsional: auto-detect kalau kosong
WEBMAIL_DOMAIN = "Buat sendiri Njier di web"
DOMAIN_LIST = "candstore.my.id,companysejahtera.web.id,getzplay.my.id,getztrue.my.id,kyuboexe.codes,monsdigital.tech"
# Secrets (akan di-set via dashboard atau wrangler secret)
# BOT_TOKEN → wrangler secret put BOT_TOKEN
# zdmbut ADMIN_PASSWORD → wrangler secret put ADMIN_PASSWORD
